version: '2'
services:
  etcd:
    image: rancher/none
    labels:
      io.rancher.operator: etcd
      io.rancher.operator.etcd.size: ${SIZE}
      io.rancher.operator.etcd.version: ${VERSION}
      io.rancher.operator.etcd.paused: ${PAUSED}
      io.rancher.operator.etcd.antiaffinity: ${ANTIAFFINITY}
      # critically important, prevents troll containers
      io.rancher.service.selector.container: app=nevergonnagiveyouup
    network_mode: none