.catalog:
  name: etcd
  version: v0.2.4-rancher
  minimum_rancher_version: v1.1.3
  questions:
  - variable: SIZE
    label: Size
    required: true
    default: 3
    type: int
  - variable: VERSION
    label: Version
    required: true
    default: 3.1.5
    type: enum
    options:
    - 3.1.5
    - 3.1.4
    - 3.1.3
    - 3.1.2
    - 3.1.1
    - 3.1.0
    - 3.0.17
    - 3.0.16
    - 3.0.15
    - 3.0.14
    - 3.0.13
    - 3.0.12
    - 3.0.11
    - 3.0.10
    - 3.0.9
    - 3.0.8
    - 3.0.7
    - 3.0.6
    - 3.0.5
    - 3.0.4
    - 3.0.3
    - 3.0.2
    - 3.0.1
    - 3.0.0
  - variable: PAUSED
    label: Paused
    required: true
    default: false
    type: boolean
  - variable: ANTIAFFINITY
    label: AntiAffinity
    required: true
    default: true
    type: boolean
etcd:
  scale: 0